export const data  = [
    {
    id:1,
    title:'Buzo Canguro Beige ',
    genero:'Hombre',
    description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Tempora dicta, delectus nihil quam cupiditate, officia repellendus quod eos ab quis eius dolorum aperiam nostrum consectetur, quos adipisci veniam. Architecto, suscipit!',
    talles:'Talles: Xl - L - M - S',
    Img:"https://imageshack.com/i/pme0JVQQj",
    price:9000,
    stock:20,
    temporada:'Invierno',
    category:1,
    },
    {
    id:2,
    title:'Buzo Canguro Black',
    genero:'Hombre',
    description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Tempora dicta, delectus nihil quam cupiditate, officia repellendus quod eos ab quis eius dolorum aperiam nostrum consectetur, quos adipisci veniam. Architecto, suscipit!',
    talles:'Talles: Xl - L - M - S',
    Img:"https://imageshack.com/i/po3MNChEj",
    price:10000,
    stock:30,
    temporada:'Invierno',
    category:1,
    },
    {
    id:3,   
    title:'Buzo Canguro Grey',
    genero:'Mujer',
    description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Tempora dicta, delectus nihil quam cupiditate, officia repellendus quod eos ab quis eius dolorum aperiam nostrum consectetur, quos adipisci veniam. Architecto, suscipit!',
    talles:'Talles: Xl - L - M - S',
    Img:"https://imageshack.com/i/pmGq5T4vj",
    price:8000,
    stock:30,
    temporada:'Invierno',
    category:2,
    },
    {
    id:4,
    title:'Sweater brown',
    genero:'Mujer',
    description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Tempora dicta, delectus nihil quam cupiditate, officia repellendus quod eos ab quis eius dolorum aperiam nostrum consectetur, quos adipisci veniam. Architecto, suscipit!',
    talles:'Talles: Xl - L - M - S',
    Img:"https://imageshack.com/i/pnT4yavHj",
    price:7000,
    stock:40,
    temporada:'primavera',
    category:2,
    },
    {
    id:5,
    title:'Buzo Beige',
    genero:'Mujer',
    description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Tempora dicta, delectus nihil quam cupiditate, officia repellendus quod eos ab quis eius dolorum aperiam nostrum consectetur, quos adipisci veniam. Architecto, suscipit!',
    talles:'Talles: Xl - L - M - S',
    Img:"https://imageshack.com/i/po6uqjkTj",
    price:11000,
    stock:2,
    temporada:'Invierno',
    category:30,    
    },
    {
    id:6,
    title:'Buzo Grey',
    genero:' Hombre',
    description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Tempora dicta, delectus nihil quam cupiditate, officia repellendus quod eos ab quis eius dolorum aperiam nostrum consectetur, quos adipisci veniam. Architecto, suscipit!',
    talles:'Talles: Xl - L - M - S',
    Img:"https://imageshack.com/i/pm5PVKepj", 
    price:12000,
    stock:50,
    temporada:'Invierno',
    category:1,
    },
    {
    id:8,
    title:'Camisa White ',
    genero:'Mujer',
    description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Tempora dicta, delectus nihil quam cupiditate, officia repellendus quod eos ab quis eius dolorum aperiam nostrum consectetur, quos adipisci veniam. Architecto, suscipit!',
    talles:'Talles: Xl - L - M - S',
    Img:"https://imageshack.com/i/pntv0BMtj",
    price:15000,
    stock:15, 
    temporada:'Verano',
    category:2,
    },
    {
    id:9,
    title:'Enterito Green ',
    genero:'Hombre',
    description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Tempora dicta, delectus nihil quam cupiditate, officia repellendus quod eos ab quis eius dolorum aperiam nostrum consectetur, quos adipisci veniam. Architecto, suscipit!',
    talles:'Talles: Xl - L - M - S',
    Img:"https://imageshack.com/i/poAlGolqj",
    price:20000, 
    stock:10,
    temporada:'Verano',
    category:3,
    },
    {
    id:10,
    title:'Remera White',
    genero:'Hombre',
    description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Tempora dicta, delectus nihil quam cupiditate, officia repellendus quod eos ab quis eius dolorum aperiam nostrum consectetur, quos adipisci veniam. Architecto, suscipit!',
    talles:'Talles: Xl - L - M - S',
    Img:"https://imageshack.com/i/pmEn3T3Uj",
    price:6000, 
    stock:40,
    temporada:'Verano',
    category:3,
    },
    {
    id:7,
    title:'Buzo Purpura',
    genero:'Mujer',
    description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Tempora dicta, delectus nihilquam cupiditate, officia repellendus quod eos ab quis eius dolorum aperiam nostrum consectetur, quosadipisci veniam. Architecto, suscipit!',
    talles:'Talles: Xl - L - M - S',
    Img:"https://imageshack.com/i/pmvrE9pMj",
    price:11500, 
    stock:20,
    temporada:'Invierno',
    category:2,
    },
]

